### PR TITLE
Feat/update video player

### PR DESCRIPTION
**Pull request by arneroen**

### CODE REVIEW

**Comment by ArielKarlsen** [comment]
Tested and approved.Good job!

**Comment by arneroen** [comment]
[Swap VideoView to MediaPlayer](https://trello.com/c/u3Sd93A8/2-swap-videoview-to-mediaplayer)

**Comment by arneroen** [comment]
[Make the video player activity take a file location as an argument](https://trello.com/c/FtNtIPZ7/5-make-the-video-player-activity-take-a-file-location-as-an-argument)

**Comment by arneroen** [comment]
[Make the video player activity take a file location as an argument](https://trello.com/c/FtNtIPZ7/5-make-the-video-player-activity-take-a-file-location-as-an-argument)

**Pull request merged**
